MEMORY
{
  ROM : ORIGIN = 0x80000000, LENGTH = 1M
  RAM : ORIGIN = 0x80200000, LENGTH = 1M
}

REGION_ALIAS("REGION_TEXT", ROM);
REGION_ALIAS("REGION_RODATA", ROM);
REGION_ALIAS("REGION_DATA", ROM);
REGION_ALIAS("REGION_BSS", ROM);
REGION_ALIAS("REGION_HEAP", ROM);
REGION_ALIAS("REGION_STACK", ROM);
